### ISSUE TITLE
Bug with step 2?

### ISSUE THREAD

**Issue by SoftologyPro** [Vchitect/LaVie#22]
Step 1 creates the movies as per the examples.
Step 2 creates static/noisy results?  Tried on 2 PCs with a 3090 and 4090 GPU.

<img width="502" alt="Screenshot 2023-11-21 183130" src="https://github.com/Vchitect/LaVie/assets/47686889/e8f96252-2470-4895-9b2e-72dea5ffd9b3">

**Comment by wyhsirius** [comment]
@SoftologyPro  Thanks for pointing out. We have fixed this bug, please try the updated code.

**Comment by SoftologyPro** [comment]
Thank you.  Works fine now.
