### ISSUE TITLE
About long video generation

### ISSUE THREAD

**Issue by Jjihwan** [Vchitect/LaVie#46]
I want to express my appreciation for your impressive project and its release.
Thank you for your valuable contribution. :)

I am particularly interested in exploring long video generation,
and I was wondering if you could share your fine-tuned models for research purpose.

Thank you.

**Comment by Jjihwan** [comment]
Thanks for your help! :)

**Comment by maxin-cn** [comment]
> �Thanks for your help! :)

We may push a 32 frame LaVie model, please stay tuned ~

**Comment by Jjihwan** [comment]
SEINE was what I just looking for 😆
Thanks for notification!
