### ISSUE TITLE
config.json does not exist

### ISSUE THREAD

**Issue by nguyendung1612** [Vchitect/LaVie#53]
Thanks for your contributions.

When running step 2, I got this error about the pretrained model. Could you please check it out?

![error](https://github.com/Vchitect/LaVie/assets/43613837/438391f3-367d-4c57-8b99-5cad936ebd20)

**Comment by maxin-cn** [comment]
> Thanks for your contributions.
> 
> When running step 2, I got this error about the pretrained model. Could you please check it out?
> 
> ![error](https://private-user-images.githubusercontent.com/43613837/293869012-438391f3-367d-4c57-8b99-5cad936ebd20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDU3MjMsIm5iZiI6MTcwNDM0NTQyMywicGF0aCI6Ii80MzYxMzgzNy8yOTM4NjkwMTItNDM4MzkxZjMtMzY3ZC00YzU3LThiOTktNWNhZDkzNmViZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA1MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYzA1NGEzYjY2OTU4YmNkYjhmMGFmYjZlMzVhMzMyMzc3NzljMzI2ZTgwZjhkMzNmYzUxM2FlMTBkNTczZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dilhCzHOr23J891zi18gJ_OaHMMtu5OlZ7AUfVxDGY)
It looks like you're running under windows. Check under `... /pretrained_models/lavie_interpolation.pt\unet\config` whether the path is recognized by windows or whether the path is correct.

**Comment by nguyendung1612** [comment]
> > Thanks for your contributions.
> > When running step 2, I got this error about the pretrained model. Could you please check it out?
> > ![error](https://private-user-images.githubusercontent.com/43613837/293869012-438391f3-367d-4c57-8b99-5cad936ebd20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDU3MjMsIm5iZiI6MTcwNDM0NTQyMywicGF0aCI6Ii80MzYxMzgzNy8yOTM4NjkwMTItNDM4MzkxZjMtMzY3ZC00YzU3LThiOTktNWNhZDkzNmViZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA1MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYzA1NGEzYjY2OTU4YmNkYjhmMGFmYjZlMzVhMzMyMzc3NzljMzI2ZTgwZjhkMzNmYzUxM2FlMTBkNTczZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dilhCzHOr23J891zi18gJ_OaHMMtu5OlZ7AUfVxDGY)
> > It looks like you're running under windows. Check under `... /pretrained_models/lavie_interpolation.pt\unet\config` whether the path is recognized by windows or whether the path is correct.

Thanks for your reply.
![Screenshot 2024-01-08 113722](https://github.com/Vchitect/LaVie/assets/43613837/46216179-e007-4dde-9fc4-152a96edebb6)

I checked for its existence and the result was true.

**Comment by jiuyouyun9** [comment]
Try changing LaVie-main\interpolation\configs\sample.yaml, line 3, to be like: ckpt_path: '../pretrained_models/stable-diffusion-v1-4'

**Comment by nguyendung1612** [comment]
> Try changing LaVie-main\interpolation\configs\sample.yaml, line 3, to be like: ckpt_path: '../pretrained_models/stable-diffusion-v1-4'

It's working. Thanks for your support.
