### ISSUE TITLE
Some typos in config files.

### ISSUE THREAD

**Issue by MqLeet** [Vchitect/LaVie#57]
Hi, @wyhsirius , thanks for your great work "LaVie"!

I found some typos in config files while running the code, they are:

1. ~/LaVie/interpolation/configs/sample.yaml

```yaml
 # ckpt_path: "../pretrained_models/lavie_interpolation.pt"
 ckpt_path: "../pretrained_models/stable-diffusion-v1-4" 
```

2. ~/LaVie/vsr/configs/sample.yaml
```yaml
# ckpt_path: "../pretained_models/lavie_vsr.pt"
ckpt_path: "../pretrained_models/lavie_vsr.pt"
```

Best wishes,
MqLeet.

**Comment by wyhsirius** [comment]
@MqLeet Thanks for pointing out! 

For 1, I kept the original sample.yaml and modified ~/LaVie/interpolation/sample.py, please check.

For 2, typo fixed.

If you have found other bugs, don't hesitate to contact.

**Comment by MqLeet** [comment]
Thanks for your reply!

Now everything is OK and I will close this issue!
